name: CoreProtectModFix
version: ${version}
main: org.windy.coreProtectModFix.CoreProtectModFix
api-version: '1.20'
depend: [CoreProtect]
commands:
  comod:
    description: Commands for TeleportOffset plugin.